<a href="https://colab.research.google.com/github/mailtokeerthibhuvanasri-ctrl/ML_LAB_2026-27/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Pandas Python Library**

**Introduction to Pandas**

Pandas is an open-source software library written for the Python programming language, primarily used for data manipulation and analysis. It provides powerful and flexible data structures designed to make working with tabular and time-series data both easy and intuitive.

**Key features and functionalities of Pandas include: Data Structures:**

Pandas introduces two primary data structures:

**Series**: A one-dimensional labeled array capable of holding any data type. It can be thought of as a single column in a spreadsheet.

**DataFrame**: A two-dimensional labeled data structure with columns of potentially different data types. It is similar to a spreadsheet or SQL table, providing a powerful way to represent and manipulate tabular data.

**What is pandas used for**?

pandas is used throughout the data analysis workflow. With pandas, you can:

Import datasets from databases, spreadsheets, comma-separated values (CSV) files, and more.
Clean datasets, for example, by dealing with missing values.
Tidy datasets by reshaping their structure into a suitable format for analysis.
Aggregate data by calculating summary statistics such as the mean of columns, correlation between them, and more.
Visualize datasets and uncover insights.

**Importing data in pandas**

In [1]:


import pandas as pd

**Importing CSV files**

Use **read_csv()** with the path to the CSV file to read a comma-separated values file

In [2]:

df=pd.read_csv("/content/sample_data/california_housing_train.csv")

In [3]:

df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [4]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [5]:

df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [6]:

df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

**Importing Excel files**

In [13]:
df2=pd.read_excel("/content/student_records.xlsx")

In [14]:

df2.head()

           Name Roll Number  Marks  Year
0  Aarav Sharma        R001     87  2024
1   Priya Patel        R002     92  2024
2   Rohan Verma        R003     76  2023
3  Ananya Singh        R004     65  2023
4    Vikram Rao        R005     81  2025

In [16]:
df2.tail()

           Name Roll Number  Marks  Year
5  Ishita Gupta        R006     95  2025
6   Karan Mehta        R007     58  2024
7   Sneha Reddy        R008     73  2023
8  Aditya Kumar        R009     88  2025
9    Divya Nair        R010     69  2024

In [17]:
df2.describe()

           Marks         Year
count  10.000000    10.000000
mean   78.400000  2024.000000
std    12.258331     0.816497
min    58.000000  2023.000000
25%    70.000000  2023.250000
50%    78.500000  2024.000000
75%    87.750000  2024.750000
max    95.000000  2025.000000

In [18]:

df2.columns

Index(['Name', 'Roll Number', 'Marks', 'Year'], dtype='object')

**Importing JSON Files**

In [19]:
df3=pd.read_json("/content/students.json")

In [20]:

df3.head()

           name roll_number  marks  year
0  Aarav Sharma        R001     87  2024
1   Priya Patel        R002     92  2024
2   Rohan Verma        R003     76  2023
3  Ananya Singh        R004     65  2023
4    Vikram Rao        R005     81  2025

In [21]:
df3.tail()

           name roll_number  marks  year
5  Ishita Gupta        R006     95  2025
6   Karan Mehta        R007     58  2024
7   Sneha Reddy        R008     73  2023
8  Aditya Kumar        R009     88  2025
9    Divya Nair        R010     69  2024

In [22]:
df3.describe()

           marks         year
count  10.000000    10.000000
mean   78.400000  2024.000000
std    12.258331     0.816497
min    58.000000  2023.000000
25%    70.000000  2023.250000
50%    78.500000  2024.000000
75%    87.750000  2024.750000
max    95.000000  2025.000000

In [23]:

df3.columns

Index(['name', 'roll_number', 'marks', 'year'], dtype='object')